### ISSUE TITLE
does not work on OpenBSD amd64

### ISSUE THREAD

**Issue by tljm** [materialsvirtuallab/pyhull#12]
It compiles with some warnings, can be imported to python but when used Segementation fault happens. Brief inspection of dumped core suggests problems with libc/stdio/fgets - though I am not an expert in gdb so I might be wrong. What info do you need to try to tackle this issue?

**Comment by shyuep** [comment]
Unfortunately, I do not have access to an OpenBSD machine to try to debug this. Maybe you can give me an idea of what you intend to use pyhull for and I can try to give some suggestions?

**Comment by tljm** [comment]
Thank you for prompt reply.
I want to use pyhull for a very simple task. I have many sets of points 
in 3D space and I want to look for vertices of convex hull. That's all.
Since I'm writing an application in python, pyhull is a very convenient 
and natural way of doing that.
Any way, to circumvent my problems, I will directly call qhull. Or, 
perhaps, you have other suggestions?

By the way, have you succeed to run pyhull on any BSD system, not 
necessarily on OpenBSD?

**Comment by shyuep** [comment]
As stated in the docs,  recent versions of scipy has a scipy.spatial.ConvexHull that works pretty much the same,  though scipy is a fairly large install. 

I have never done any BSD installs. I know pyhull works on Mac Darwin (which has BSD components) and most Linux systems we have tested.

**Comment by tljm** [comment]
OK. I should read docs more carefully!
I'm using scipy as well so the size of scipy installation does not 
matter much.
Thank you very much, you have saved me a lot of work.
