### ISSUE TITLE
compiling

### ISSUE THREAD

**Issue by setten** [materialsvirtuallab/pyhull#7]
Hi,

I found that icc has a problem compiling the qhull libraries. The setup of pyhull takes the CC environmental to compile. When I compile qhull from source, it always uses gcc. Just exporting CC=gcc before running pyhull setup solves the issue.

Best,
Michiel

**Comment by JensTimmerman** [comment]
actually, I got it to compile with icc, using this patch: https://github.com/hpcugent/easybuild-easyconfigs/blob/942335a9a0fa0563571bbf167cdf568df188c84b/easybuild/easyconfigs/q/Qhull/Qhull-2012.1-intel-fix.patch

**Comment by shyuep** [comment]
Thanks. I integrated this into the qhull src and pushed a new release.

**Comment by JensTimmerman** [comment]
Well, I'm not sure why that code was there in the first place, it looks like you're trying to discourage us from compiling with icc?

**Comment by shyuep** [comment]
The source code for qhull is not from me. I obtained it directly from qhull.org. So I wasn't sure why that code was there in the first place as well. 

I only wrote the python wrapper (pyhull) which adds a high level interface to qhull.
