### ISSUE TITLE
Installation problem in ubuntu

### ISSUE THREAD

**Issue by paragbansal** [materialsvirtuallab/pyhull#8]
I am getting the following errors during easy-installation of Pyhull.
--
parag@Dabba:~$ sudo easy_install pyhull
Searching for pyhull
Reading https://pypi.python.org/simple/pyhull/
Best match: pyhull 1.4.3
Downloading https://pypi.python.org/packages/source/p/pyhull/pyhull-1.4.3.tar.gz#md5=25e62181a8430f102b7d853aaaec3401
Processing pyhull-1.4.3.tar.gz
Writing /tmp/easy_install-PaeyF9/pyhull-1.4.3/setup.cfg
Running pyhull-1.4.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-PaeyF9/pyhull-1.4.3/egg-dist-tmp-9RNC0Y
warning: no files found matching '*.md'
warning: no files found matching '*.c'
no previously-included directories found matching '**/tests'
src/_pyhull.c:28:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

P.S. - I am unable to fix this. Is there any other way to install pyhull.

**Comment by uoyssim** [comment]
if **_sudo apt install python-dev_** doesn't work, please check your python version & install python{version}-dev
```
# python version: 3.6
sudo apt install python3.6-dev
```
